services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://root:secret@localhost:27017/?authSource=admin", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:${PORT:-3000}/books || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 20
    environment:
      PORT: ${PORT:-3000}
      STRING_connection_DB: ${STRING_connection_DB:-mongodb://root:secret@mongo:27017/books?authSource=admin}


  tests:
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    depends_on:
      app:
        condition: service_healthy
    volumes:
      # tu colección y environment están en ./tests
      - ./tests:/tests/tests:ro
      # los resultados de allure van a ./allure-results
      - ./allure-results:/tests/allure-results
    command: >
      sh -lc "newman run /tests/tests/collection.json
      -e /tests/tests/env.local.json
      -r cli,allure
      --reporter-allure-export /tests/allure-results"

  allure:
    image: frankescobar/allure-docker-service
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/default-reports

  allure-ui:
    image: frankescobar/allure-docker-service-ui:7.0.1
    ports:
      - "9090:8080"   # cambiaste 8080→9090 porque tenés Postgres usando 8080
    environment:
      - ALLURE_DOCKER_API_URL=http://allure:5050
      - ROUTER_BASE_NAME=/
    depends_on:
      - allure

volumes:
  mongo-data:
