name: API Tests (Docker + Newman + Allure)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # (Opcional) acelera builds si tu app es pesada
      # - uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/.npm
      #     key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Build images
        run: docker compose build

      - name: Start app stack (mongo + app)
        run: docker compose up -d mongo app

      - name: Run Newman tests
        run: docker compose up --exit-code-from tests tests

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      # (Opcional) Generar HTML de Allure en CI y subirlo como artefacto
      - name: Generate Allure HTML
        if: always()
        run: |
          docker run --rm \
            -v "$PWD/allure-results:/allure-results:ro" \
            -v "$PWD/allure-report:/allure-report" \
            frankescobar/allure-docker-service \
            /bin/sh -lc "allure generate /allure-results --clean -o /allure-report"
      - name: Upload Allure HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
