permissions:
  contents: read
  pages: write
  id-token: write

name: API Tests (Docker + Newman + Allure)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build images
        run: docker compose build

      - name: Start app stack (mongo + app)
        run: docker compose up -d mongo app

      - name: Run Newman tests
        run: docker compose up --exit-code-from tests tests

      - name: Prepare report dirs
        if: always()
        run: |
          mkdir -p allure-results
          mkdir -p allure-report

      - name: Generate Allure HTML
        if: always()
        run: |
          docker run --rm -u 0 \
            -v "$PWD/allure-results:/allure-results:ro" \
            -v "$PWD/allure-report:/allure-report" \
            frankescobar/allure-docker-service \
            /bin/sh -lc "allure generate /allure-results --clean -o /allure-report"

      # <-- AQUI van los pasos de Pages
      - name: Configure Pages
        if: always()
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report
  deploy:
    needs: test
    if: always()
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
